CREATE TABLE IF NOT EXISTS teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    display_name VARCHAR(255),
    logo_url VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    nickname VARCHAR(255),
    favorite_team_id BIGINT,
    visit_count INTEGER DEFAULT 0,
    last_visit_date TIMESTAMP,
    FOREIGN KEY (favorite_team_id) REFERENCES teams(id)
);

CREATE TABLE IF NOT EXISTS history_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL,
    event_month INTEGER,
    event_day INTEGER,
    event_year INTEGER,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    image_url VARCHAR(255),
    type VARCHAR(50),
    FOREIGN KEY (team_id) REFERENCES teams(id)
);
